users:
  - default
  - name: jason
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGHZns1IFaYhzV7uBjsWYm+TbUF+eEYVoGKEd9Elz3jF jasondoze@jd.attlocal.net
      
