users:
  - default
  - name: jason
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGj2JXOPktbGiQRzLcxsdVcGbV89cRz8NBWe9qu5AXvo jasondoze@jd.attlocal.net
      
